//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Design_Examples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Software_Design_Examples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Coke_Round_Logo {
            get {
                object obj = ResourceManager.GetObject("Coke_Round_Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Inventories&quot;: [{
        ///
        ///		&quot;Id&quot;: &quot;001&quot;,
        ///		&quot;ProductName&quot;: &quot;Coke&quot;,
        ///		&quot;MaxAvailable&quot;: &quot;100&quot;,
        ///		&quot;RefillAmount&quot;: &quot;40&quot;,
        ///		&quot;NumberAvailable&quot;: &quot;72&quot;,
        ///		&quot;Price&quot;: &quot;1.75&quot;
        ///
        ///	}, {
        ///
        ///		&quot;Id&quot;: &quot;002&quot;,
        ///		&quot;ProductName&quot;: &quot;Diet Coke&quot;,
        ///		&quot;MaxAvailable&quot;: &quot;100&quot;,
        ///		&quot;RefillAmount&quot;: &quot;40&quot;,
        ///		&quot;NumberAvailable&quot;: &quot;63&quot;,
        ///		&quot;Price&quot;: &quot;1.75&quot;
        ///
        ///	}, {
        ///		&quot;Id&quot;: &quot;003&quot;,
        ///		&quot;ProductName&quot;: &quot;Water&quot;,
        ///		&quot;MaxAvailable&quot;: &quot;100&quot;,
        ///		&quot;RefillAmount&quot;: &quot;40&quot;,
        ///		&quot;NumberAvailable&quot;: &quot;84&quot;,
        ///		&quot;Price&quot;: &quot;1.25&quot;
        ///	}, {
        ///		&quot;Id&quot;: &quot;004&quot;,
        ///		&quot;ProductName&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config1 {
            get {
                return ResourceManager.GetString("Config1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Inventories&quot;: [{
        ///
        ///		&quot;Id&quot;: &quot;001&quot;,
        ///		&quot;ProductName&quot;: &quot;Coke&quot;,
        ///		&quot;MaxAvailable&quot;: &quot;100&quot;,
        ///		&quot;RefillAmount&quot;: &quot;40&quot;,
        ///		&quot;NumberAvailable&quot;: &quot;72&quot;,
        ///		&quot;Price&quot;: &quot;1.75&quot;
        ///
        ///	}, {
        ///
        ///		&quot;Id&quot;: &quot;002&quot;,
        ///		&quot;ProductName&quot;: &quot;Diet Coke&quot;,
        ///		&quot;MaxAvailable&quot;: &quot;100&quot;,
        ///		&quot;RefillAmount&quot;: &quot;40&quot;,
        ///		&quot;NumberAvailable&quot;: &quot;63&quot;,
        ///		&quot;Price&quot;: &quot;1.75&quot;
        ///
        ///	}, {
        ///		&quot;Id&quot;: &quot;003&quot;,
        ///		&quot;ProductName&quot;: &quot;Water&quot;,
        ///		&quot;MaxAvailable&quot;: &quot;100&quot;,
        ///		&quot;RefillAmount&quot;: &quot;40&quot;,
        ///		&quot;NumberAvailable&quot;: &quot;84&quot;,
        ///		&quot;Price&quot;: &quot;1.25&quot;
        ///	}, {
        ///		&quot;Id&quot;: &quot;004&quot;,
        ///		&quot;ProductName&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config2 {
            get {
                return ResourceManager.GetString("Config2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Diet_Coke_Round_Logo {
            get {
                object obj = ResourceManager.GetObject("Diet_Coke_Round_Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lemonade_Round_Logo {
            get {
                object obj = ResourceManager.GetObject("Lemonade_Round_Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Transparent {
            get {
                object obj = ResourceManager.GetObject("Transparent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Water_Round_Logo {
            get {
                object obj = ResourceManager.GetObject("Water_Round_Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
